DROP TABLE IF EXISTS IntakeEvents;
DROP TABLE IF EXISTS Drinks;
DROP TABLE IF EXISTS Foods;
DROP TABLE IF EXISTS Users;


CREATE TABLE Users (
    userID INT NOT NULL
);

CREATE TABLE Foods (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , loggedBy INT NOT NULL
  , description TEXT NOT NULL
  , amount TEXT NOT NULL
);

CREATE TABLE Drinks (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , loggedBy INT NOT NULL
  , description TEXT NOT NULL
  , amount TEXT NOT NULL
);

CREATE TABLE IntakeEvents (
    id INTEGER PRIMARY KEY AUTO_INCREMENT
  , loggedBy INT NOT NULL
  , mealType TEXT NOT NULL
  , loggedAt TEXT NOT NULL
);